export const data = [
    {
      batchNumber: 'ABX123',
      medecineName: 'Dolo',
      category: 'Tablet',
      expiryDate: '2030-12-24',
      maxRetailPrice: 10,
      discount: 5,
      unit: 1,
      price: 9.5,
      rackNumber: 6,
      description: 'This is a cold and fever tablet',
      openStock: 10,
      reorderLevel: 100,
    },
    {
      batchNumber: 'XYZ456',
      medecineName: 'Aspirin',
      category: 'Tablet',
      expiryDate: '2022-10-15',
      maxRetailPrice: 8,
      discount: 3,
      unit: 1,
      price: 7.5,
      rackNumber: 4,
      description: 'Pain relief tablet',
      openStock: 15,
      reorderLevel: 50,
    },
    {
      batchNumber: 'ABX123',
      medecineName: 'Dolo',
      category: 'Tablet',
      expiryDate: '2030-12-24',
      maxRetailPrice: 10,
      discount: 5,
      unit: 1,
      price: 9.5,
      rackNumber: 6,
      description: 'This is a cold and fever tablet',
      openStock: 10,
      reorderLevel: 100,
    },
    {
      batchNumber: 'ABX123',
      medecineName: 'Dolo',
      category: 'Tablet',
      expiryDate: '2030-12-24',
      maxRetailPrice: 10,
      discount: 5,
      unit: 1,
      price: 9.5,
      rackNumber: 6,
      description: 'This is a cold and fever tablet',
      openStock: 10,
      reorderLevel: 100,
    },
    {
      batchNumber: 'ABX123',
      medecineName: 'Dolo',
      category: 'Tablet',
      expiryDate: '2030-12-24',
      maxRetailPrice: 10,
      discount: 5,
      unit: 1,
      price: 9.5,
      rackNumber: 6,
      description: 'This is a cold and fever tablet',
      openStock: 10,
      reorderLevel: 100,
    },
    {
      batchNumber: 'ABX123',
      medecineName: 'Dolo',
      category: 'Tablet',
      expiryDate: '2030-12-24',
      maxRetailPrice: 10,
      discount: 5,
      unit: 1,
      price: 9.5,
      rackNumber: 6,
      description: 'This is a cold and fever tablet',
      openStock: 10,
      reorderLevel: 100,
    },
    // Add more objects as needed
  ];